### ISSUE TITLE
[BUG] julia-client 0.8.10 does not open plots/docs/workspace panes

### ISSUE THREAD

**Issue by yha** [JunoLab/Juno.jl#326]
## Details
- Atom version: 1.38.2
- Julia version: 1.1.1
- OS: Windows 10
- Package versions:
  - Atom.jl: 0.8.7
  - julia-client: 0.8.10
  - ink: 0.10.11

### Steps to reproduce
Since upgrading julia-client to 0.8.10, the plots, docs and workspace panes do not open on startup or when running the "Restore default layout" command. 
The error console says this once after boot, and again on each "Restore default layout":
```
Uncaught (in promise) TypeError: pane(...).open(...).catch(...).finally is not a function
    at openPanesHelper (layout.js:89)
    at openPanes (layout.js:69)
    at layout.js:107
    at <anonymous>
openPanesHelper @ layout.js:89
openPanes @ layout.js:69
(anonymous) @ layout.js:107
Promise resolved (async)
restoreDefaultLayout @ layout.js:101
julia-client:restore-default-layout @ commands.coffee:96
handleCommandEvent @ VM22 <embedded>:11
didConfirmSelection @ VM22 <embedded>:11
confirmSelection @ VM22 <embedded>:11
core:confirm @ VM22 <embedded>:11
handleCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.dispatchCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.handleKeyboardEvent @ VM22 <embedded>:11
handleDocumentKeyEvent @ VM22 <embedded>:11
```

Opening the panes manually or by plotting does work.

**Comment by pfitzseb** [comment]
I can't repro this. Can you provide the output of the `Julia Client: Debug Info` command?

**Comment by yha** [comment]
`Julia Client: Debug Info` output:

```
# Atom:
Version: 1.38.2
Dev Mode: false
Official Release: true
{
  "http_parser": "2.7.0",
  "node": "8.9.3",
  "v8": "6.1.534.41",
  "uv": "1.15.0",
  "zlib": "1.2.11",
  "ares": "1.10.1-DEV",
  "modules": "57",
  "nghttp2": "1.25.0",
  "openssl": "1.0.2n",
  "electron": "2.0.18",
  "chrome": "61.0.3163.100"
}
# julia-client:
Version: 0.8.10
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "noAutoParenthesis": true
  },
  "juliaPath": "C:\\Users\\sternlab\\AppData\\Local\\Julia-1.1.1\\bin\\julia.exe",
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}


# ink:
Version: 0.10.11
Config:
undefined


# uber-juno:
Version: 0.2.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.1
Config:
undefined


# language-weave:not installed


# indent-detective:
Version: 0.3.3
Config:
undefined


Could not connect to Julia.
```

When running the command, the console says
```
julia> ┌ Warning: Atom.jl: unrecognised message reportinfo.
└ @ Atom C:\Users\sternlab\.julia\packages\Atom\cR6bU\src\comm.jl:171
```

**Comment by aviatesk** [comment]
The seems to be caused by the part I've implemented, but I can't reproduce this and not sure why this happens.
Restarting Atom may solve this.

And note your `Atom.jl` versions is not the latest one, and updating Atom.jl to `v0.8.8` would solve the last warning at least.

**Comment by yha** [comment]
Upgrading `Atom.jl` got rid of that warning, but didn't solve the issue. I also tried `atom --clear-window-state`, which didn't help.

**Comment by pfitzseb** [comment]
Might be fixed by now. Please reopen if that's not the case.
